apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # Use this if running Prometheus in Docker
    # url: http://host.docker.internal:9090  # Use this if Prometheus is running on host
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST