# MongoDB
version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: card-game-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGODB_DATABASE=cardgame
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  mongodb_data:
